/*
 * Outcome Billing Dashboard – Void Terminal Design
 * Shows value generated per agent, performance fees, credits, billing forecast
 * Core to the Services-as-a-Software / outcome-based pricing model
 */
import { motion } from "framer-motion";
import {
  DollarSign,
  TrendingUp,
  Zap,
  Calendar,
  BarChart3,
  ArrowUpRight,
  Crown,
  CreditCard,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Cell,
  LineChart,
  Line,
  Legend,
  ComposedChart,
  Area,
} from "recharts";
import {
  billingData,
  agentAttribution,
  valueVsCostData,
  currentPlan,
} from "@/lib/mockData";

const containerVariants = {
  hidden: { opacity: 0 },
  show: { opacity: 1, transition: { staggerChildren: 0.06 } },
};

const itemVariants = {
  hidden: { opacity: 0, y: 12 },
  show: { opacity: 1, y: 0, transition: { duration: 0.3 } },
};

function CustomTooltip({ active, payload, label }: any) {
  if (!active || !payload?.length) return null;
  return (
    <div className="bg-popover border border-border rounded-lg px-3 py-2 shadow-lg">
      <p className="text-xs text-muted-foreground font-mono mb-1">{label}</p>
      {payload.map((p: any, i: number) => (
        <p key={i} className="text-sm font-mono font-semibold" style={{ color: p.color }}>
          {p.name}: ${p.value?.toLocaleString()}
        </p>
      ))}
    </div>
  );
}

export default function OutcomeBilling() {
  const valueToFeeRatio = (billingData.totalValueGenerated / billingData.estimatedBill).toFixed(1);

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-display font-bold text-foreground">
            Outcome Billing Dashboard
          </h1>
          <p className="text-sm text-muted-foreground mt-1">
            Track value generated by your agent workforce vs. fees paid. You only pay for outcomes.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Badge variant="outline" className="text-xs font-mono border-primary/30 text-primary bg-primary/5 gap-1">
            <Crown className="w-3 h-3" />
            {currentPlan.tier}
          </Badge>
          <Badge variant="outline" className="text-xs font-mono border-border text-muted-foreground">
            <Calendar className="w-3 h-3 mr-1" />
            {billingData.currentMonth}
          </Badge>
        </div>
      </div>

      {/* Top Metrics */}
      <motion.div
        variants={containerVariants}
        initial="hidden"
        animate="show"
        className="grid grid-cols-2 lg:grid-cols-4 gap-4"
      >
        <motion.div variants={itemVariants}>
          <Card className="bg-card border-border">
            <CardContent className="p-4">
              <div className="flex items-start justify-between">
                <div className="space-y-1.5">
                  <p className="text-xs text-muted-foreground uppercase tracking-wider">Value Generated</p>
                  <p className="text-2xl font-mono font-bold text-profit">
                    ${billingData.totalValueGenerated.toLocaleString()}
                  </p>
                  <div className="flex items-center gap-1">
                    <ArrowUpRight className="w-3 h-3 text-profit" />
                    <span className="text-xs font-mono text-profit">+13.4% vs last month</span>
                  </div>
                </div>
                <div className="w-9 h-9 rounded-lg bg-profit/10 flex items-center justify-center">
                  <TrendingUp className="w-4.5 h-4.5 text-profit" />
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        <motion.div variants={itemVariants}>
          <Card className="bg-card border-border">
            <CardContent className="p-4">
              <div className="flex items-start justify-between">
                <div className="space-y-1.5">
                  <p className="text-xs text-muted-foreground uppercase tracking-wider">Performance Fee</p>
                  <p className="text-2xl font-mono font-bold text-foreground">
                    ${billingData.performanceFeesAccrued.toLocaleString()}
                  </p>
                  <p className="text-xs font-mono text-muted-foreground">10% of agent P&L</p>
                </div>
                <div className="w-9 h-9 rounded-lg bg-primary/10 flex items-center justify-center">
                  <DollarSign className="w-4.5 h-4.5 text-primary" />
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        <motion.div variants={itemVariants}>
          <Card className="bg-card border-border">
            <CardContent className="p-4">
              <div className="flex items-start justify-between">
                <div className="space-y-1.5">
                  <p className="text-xs text-muted-foreground uppercase tracking-wider">Estimated Bill</p>
                  <p className="text-2xl font-mono font-bold text-foreground">
                    ${billingData.estimatedBill.toLocaleString()}
                  </p>
                  <p className="text-xs font-mono text-muted-foreground">${currentPlan.monthlyFee} access + fees</p>
                </div>
                <div className="w-9 h-9 rounded-lg bg-primary/10 flex items-center justify-center">
                  <CreditCard className="w-4.5 h-4.5 text-primary" />
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        <motion.div variants={itemVariants}>
          <Card className="bg-card border-border">
            <CardContent className="p-4">
              <div className="flex items-start justify-between">
                <div className="space-y-1.5">
                  <p className="text-xs text-muted-foreground uppercase tracking-wider">Value/Cost Ratio</p>
                  <p className="text-2xl font-mono font-bold text-primary">
                    {valueToFeeRatio}x
                  </p>
                  <p className="text-xs font-mono text-profit">You earn {valueToFeeRatio}x what you pay</p>
                </div>
                <div className="w-9 h-9 rounded-lg bg-primary/10 flex items-center justify-center">
                  <Zap className="w-4.5 h-4.5 text-primary" />
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>
      </motion.div>

      {/* Charts Row */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Value Generated Per Agent */}
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
        >
          <Card className="bg-card border-border">
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-display font-semibold text-foreground flex items-center gap-2">
                <BarChart3 className="w-4 h-4 text-primary" />
                Value Generated Per Agent (This Month)
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="h-[280px]">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart
                    data={agentAttribution}
                    layout="vertical"
                    barSize={18}
                    margin={{ left: 20 }}
                  >
                    <CartesianGrid
                      strokeDasharray="3 3"
                      stroke="oklch(0.25 0.015 250)"
                      horizontal={false}
                    />
                    <XAxis
                      type="number"
                      tick={{ fontSize: 10, fill: "oklch(0.6 0.015 250)", fontFamily: "'JetBrains Mono'" }}
                      axisLine={{ stroke: "oklch(0.25 0.015 250)" }}
                      tickLine={false}
                      tickFormatter={(v) => `$${(v / 1000).toFixed(0)}k`}
                    />
                    <YAxis
                      type="category"
                      dataKey="name"
                      tick={{ fontSize: 10, fill: "oklch(0.6 0.015 250)", fontFamily: "'JetBrains Mono'" }}
                      axisLine={false}
                      tickLine={false}
                      width={130}
                    />
                    <Tooltip content={<CustomTooltip />} />
                    <Bar dataKey="valueGenerated" name="Value" radius={[0, 4, 4, 0]}>
                      {agentAttribution.map((_, index) => (
                        <Cell key={index} fill="oklch(0.82 0.19 160)" fillOpacity={0.8 - index * 0.08} />
                      ))}
                    </Bar>
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Value vs Cost Over Time */}
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4 }}
        >
          <Card className="bg-card border-border">
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-display font-semibold text-foreground flex items-center gap-2">
                <TrendingUp className="w-4 h-4 text-primary" />
                Value vs. Cost (Monthly Trend)
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="h-[280px]">
                <ResponsiveContainer width="100%" height="100%">
                  <ComposedChart data={valueVsCostData}>
                    <CartesianGrid
                      strokeDasharray="3 3"
                      stroke="oklch(0.25 0.015 250)"
                      vertical={false}
                    />
                    <XAxis
                      dataKey="month"
                      tick={{ fontSize: 10, fill: "oklch(0.6 0.015 250)", fontFamily: "'JetBrains Mono'" }}
                      axisLine={{ stroke: "oklch(0.25 0.015 250)" }}
                      tickLine={false}
                    />
                    <YAxis
                      tick={{ fontSize: 10, fill: "oklch(0.6 0.015 250)", fontFamily: "'JetBrains Mono'" }}
                      axisLine={false}
                      tickLine={false}
                      tickFormatter={(v) => `$${(v / 1000).toFixed(0)}k`}
                    />
                    <Tooltip content={<CustomTooltip />} />
                    <Legend
                      wrapperStyle={{ fontSize: "11px", fontFamily: "'JetBrains Mono'" }}
                    />
                    <Area
                      type="monotone"
                      dataKey="valueGenerated"
                      name="Value Generated"
                      fill="oklch(0.82 0.19 160 / 0.15)"
                      stroke="oklch(0.82 0.19 160)"
                      strokeWidth={2}
                    />
                    <Line
                      type="monotone"
                      dataKey="costPaid"
                      name="Cost Paid"
                      stroke="oklch(0.82 0.15 195)"
                      strokeWidth={2}
                      dot={{ fill: "oklch(0.82 0.15 195)", r: 3 }}
                    />
                  </ComposedChart>
                </ResponsiveContainer>
              </div>
            </CardContent>
          </Card>
        </motion.div>
      </div>

      {/* Bottom Row: Credits + Agent Attribution Table + Billing History */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        {/* Credits & Plan */}
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.5 }}
        >
          <Card className="bg-card border-border h-full">
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-display font-semibold text-foreground flex items-center gap-2">
                <Zap className="w-4 h-4 text-primary" />
                Credits & Usage
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Agents */}
              <div className="space-y-2">
                <div className="flex justify-between text-xs">
                  <span className="text-muted-foreground">Active Agents</span>
                  <span className="font-mono text-foreground">
                    {currentPlan.agentsActive} / {currentPlan.agentsIncluded}
                  </span>
                </div>
                <Progress
                  value={(currentPlan.agentsActive / currentPlan.agentsIncluded) * 100}
                  className="h-2 bg-secondary"
                />
              </div>

              {/* Optimization Credits */}
              <div className="space-y-2">
                <div className="flex justify-between text-xs">
                  <span className="text-muted-foreground">Optimization Runs</span>
                  <span className="font-mono text-foreground">
                    {currentPlan.optimizationCreditsUsed} / Unlimited
                  </span>
                </div>
                <Progress value={30} className="h-2 bg-secondary" />
              </div>

              {/* Plan details */}
              <div className="pt-3 border-t border-border space-y-2">
                <div className="flex justify-between text-xs">
                  <span className="text-muted-foreground">Plan</span>
                  <span className="font-mono text-primary font-semibold">{currentPlan.tier}</span>
                </div>
                <div className="flex justify-between text-xs">
                  <span className="text-muted-foreground">Access Fee</span>
                  <span className="font-mono text-foreground">${currentPlan.monthlyFee}/mo</span>
                </div>
                <div className="flex justify-between text-xs">
                  <span className="text-muted-foreground">Performance Fee Rate</span>
                  <span className="font-mono text-foreground">{currentPlan.performanceFeeRate * 100}%</span>
                </div>
                <div className="flex justify-between text-xs">
                  <span className="text-muted-foreground">Additional Agent Cost</span>
                  <span className="font-mono text-foreground">${currentPlan.additionalAgentCost}/agent/mo</span>
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Agent Attribution Table */}
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.6 }}
          className="lg:col-span-2"
        >
          <Card className="bg-card border-border h-full">
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-display font-semibold text-foreground flex items-center gap-2">
                <DollarSign className="w-4 h-4 text-primary" />
                Per-Agent Attribution & Billing
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="overflow-x-auto">
                <table className="w-full text-xs font-mono">
                  <thead>
                    <tr className="border-b border-border text-muted-foreground">
                      <th className="text-left py-2 px-2">Agent</th>
                      <th className="text-right py-2 px-2">Value Generated</th>
                      <th className="text-right py-2 px-2">Perf. Fee</th>
                      <th className="text-right py-2 px-2">Trades</th>
                      <th className="text-right py-2 px-2">ROI</th>
                    </tr>
                  </thead>
                  <tbody>
                    {agentAttribution.map((agent) => (
                      <tr key={agent.agentId} className="border-b border-border/30 hover:bg-accent/30">
                        <td className="py-2.5 px-2 text-foreground font-medium">{agent.name}</td>
                        <td className="py-2.5 px-2 text-right text-profit font-semibold">
                          ${agent.valueGenerated.toLocaleString()}
                        </td>
                        <td className="py-2.5 px-2 text-right text-foreground">
                          ${agent.performanceFee.toLocaleString()}
                        </td>
                        <td className="py-2.5 px-2 text-right text-foreground">
                          {agent.tradesExecuted}
                        </td>
                        <td className="py-2.5 px-2 text-right">
                          <Badge
                            variant="outline"
                            className="text-[9px] border-profit/30 text-profit bg-profit/5"
                          >
                            +{agent.roi}%
                          </Badge>
                        </td>
                      </tr>
                    ))}
                    {/* Totals row */}
                    <tr className="border-t border-border font-semibold">
                      <td className="py-2.5 px-2 text-foreground">TOTAL</td>
                      <td className="py-2.5 px-2 text-right text-profit">
                        ${agentAttribution.reduce((s, a) => s + a.valueGenerated, 0).toLocaleString()}
                      </td>
                      <td className="py-2.5 px-2 text-right text-foreground">
                        ${agentAttribution.reduce((s, a) => s + a.performanceFee, 0).toLocaleString()}
                      </td>
                      <td className="py-2.5 px-2 text-right text-foreground">
                        {agentAttribution.reduce((s, a) => s + a.tradesExecuted, 0)}
                      </td>
                      <td className="py-2.5 px-2 text-right">—</td>
                    </tr>
                  </tbody>
                </table>
              </div>

              {/* Billing History */}
              <div className="mt-4 pt-4 border-t border-border">
                <p className="text-xs text-muted-foreground font-semibold uppercase tracking-wider mb-3">
                  Previous Billing Cycles
                </p>
                <div className="space-y-2">
                  {billingData.previousMonths.map((m) => (
                    <div key={m.month} className="flex items-center justify-between text-xs py-1.5 border-b border-border/30 last:border-0">
                      <span className="text-muted-foreground">{m.month}</span>
                      <div className="flex items-center gap-4">
                        <span className="text-profit font-semibold">+${m.valueGenerated.toLocaleString()}</span>
                        <span className="text-foreground">Fee: ${m.total.toLocaleString()}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </div>
  );
}
